# Generated by Django 4.2.1 on 2023-05-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_song_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.song')),
            ],
        ),
    ]
